import type { Metadata } from "next";
import { ButtonLink, CtaBand, PageHero, PageShell } from "../site";

export const metadata: Metadata = { title: "About", description: "Basically Income PAC is building political power for a universal cash floor in American electoral politics." };

export default function AboutPage() {
  return <PageShell>
    <PageHero eyebrow="About Basically Income PAC" title="Build the politics that basic income needs." body="We identify opportunities, pressure candidates to take meaningful positions, endorse serious UBI champions, direct resources where they may matter, and publish what we learn." actions={<><ButtonLink href="/candidates" variant="orange">Candidates & Campaigns</ButtonLink><ButtonLink href="/fund" variant="navy">Fund the Work</ButtonLink></>} aside={<><h3>Mission</h3><p>Create an American politics in which supporting a meaningful universal basic income is increasingly advantageous, expected, and actionable.</p></>} />

    <section className="content-section"><div className="content-shell prose-grid"><h2>Good ideas require political institutions.</h2><div className="prose"><p>Basic income already has research, history, advocates, experiments, and serious arguments. It needs candidates, donors, organizers, media, endorsements, and a visible constituency capable of rewarding action.</p><div className="quote-panel">Awareness is not the terminal objective. UBI must become normal, popular, funded, and politically costly to ignore.</div><p>Basically Income PAC is building the electoral layer that converts support into candidate incentives.</p></div></div></section>

    <section className="content-section alt"><div className="wide-shell"><h2>Leadership and operating responsibility.</h2><p className="lede">Leadership is presented according to the work each person owns, not as a personality cult.</p><div className="feature-grid"><article className="info-card accent"><span className="card-number">EXECUTIVE DIRECTION</span><h3>Sheridan Lund</h3><p>Executive Director. Responsible for organizational direction, political judgment, relationships, and institutional development.</p></article><article className="info-card accent"><span className="card-number">OPERATIONS</span><h3>Shael Riley</h3><p>Director of Operations. Responsible for campaign operations, communications, digital systems, and translating strategy into recurring public work.</p></article><article className="info-card"><span className="card-number">RESEARCH</span><h3>Evidence and candidate review</h3><p>Maintains policy rigor, source standards, candidate records, and the distinction between adjacent cash programs and true UBI.</p></article><article className="info-card"><span className="card-number">COMMUNITY</span><h3>Supporters and Roundtable</h3><p>The public constituency that pressures candidates, examines ideas, convenes guests, and keeps the political cycle visible.</p></article></div></div></section>

    <section className="content-section"><div className="wide-shell"><h2>Basic Income Roundtable</h2><p className="lede">A recurring public conversation with researchers, organizers, candidates, builders, and advocates working on cash, economic security, and UBI politics.</p><div className="feature-grid"><article className="action-panel"><h2>Join the live community.</h2><p>The Roundtable meets Saturdays at 11 a.m. Eastern, 10 Central, 9 Mountain, and 8 Pacific through the Basically Income PAC Clubhouse community.</p><div className="hero-actions"><a className="button button-cream" href="https://www.clubhouse.com/house/basically-income-pac-6pbvj5ds0kgs" rel="noreferrer">Open Clubhouse</a><a className="button button-outline" href="https://discord.com/invite/wEpZZYwufm" rel="noreferrer">Join Discord</a></div></article><article className="info-card accent"><h3>Press, candidates, and serious backers</h3><p>Reach the organization directly for public-position submissions, media inquiries, collaboration, or a strategic briefing.</p><div className="hero-actions"><a className="button button-navy" href="mailto:contact@basicallyincome.org">Contact the PAC</a></div></article></div></div></section>

    <CtaBand eyebrow="Build in public" title="Our scale is modest. Our mechanism is active." body="Additional capacity can materially expand how many races we examine, how quickly we launch, how strongly we support candidates, and how rigorously we report." primary={<ButtonLink href="/fund" variant="cream">Fund the Work</ButtonLink>} secondary={<ButtonLink href="/candidates" variant="outline">See the Work</ButtonLink>} />
  </PageShell>;
}
