import type { Metadata } from "next";
import { ButtonLink, PageHero, PageShell, StatusPill } from "../../site";

export const metadata: Metadata = { title: "Strategic Backer Brief", description: "A concise due-diligence brief on Basically Income PAC’s political opportunity, method, current stage, constraints, measurement, and risk." };

export default function BackerBriefPage() {
  return <PageShell>
    <PageHero eyebrow="Strategic Backer Brief · Web edition" title="Build the electoral incentive for UBI." body="A ten-minute introduction to the political opportunity, operating model, current stage, constraints, measurement, and risk of Basically Income PAC." actions={<><a className="button button-orange" href="mailto:contact@basicallyincome.org?subject=Strategic%20briefing%20request">Discuss the Brief</a><ButtonLink href="/strategy" variant="navy">Inspect the Method</ButtonLink></>} visual={{src: "/community-abundance.webp", alt: "A diverse community sharing food and public life", caption: "Build the political layer that can make greater security a normal American expectation.", tone: "navy"}} aside={<><StatusPill tone="neutral">Version 1 · August 2026</StatusPill><h3>Canonical web brief</h3><p>This page should remain more current than any downloaded or forwarded copy.</p></>} />

    <section className="content-section"><div className="content-shell prose-grid"><h2>Executive proposition.</h2><div className="prose"><p>Basic income has a serious research and advocacy ecosystem. It lacks a comparably developed electoral layer dedicated to creating candidate incentives.</p><div className="quote-panel">Basically Income PAC scans races, selects leverage, mobilizes candidate pressure, verifies meaningful movement, endorses serious champions, directs resources toward chosen opportunities, and publishes results.</div><p>Added capacity expands the number, speed, quality, and reach of those interventions.</p></div></div></section>

    <section className="content-section alt"><div className="content-shell"><h2>The mechanism</h2><p className="lede">Funding expands capacity. Capacity enables selected interventions. The PAC reports the result and improves its next allocation.</p><div className="timeline"><article className="timeline-item"><span>1 · Find</span><div><h3>Research political leverage</h3><p>Screen races, candidates, timing, constituency, media value, and decision windows.</p></div></article><article className="timeline-item"><span>2 · Move</span><div><h3>Apply organized pressure</h3><p>Build one precise ask and mobilize supporters, communications, events, and outreach.</p></div></article><article className="timeline-item"><span>3 · Reward</span><div><h3>Recognize serious commitment</h3><p>Verify movement, endorse selectively, and consider money, media, and organizational support.</p></div></article><article className="timeline-item"><span>4 · Learn</span><div><h3>Publish activity and outcome</h3><p>Separate what the PAC did, what changed, what can be attributed, and what improves next.</p></div></article></div></div></section>

    <section className="content-section"><div className="wide-shell"><h2>Why additional capital may have high marginal value.</h2><div className="feature-grid three"><article className="info-card accent"><h3>Throughput</h3><p>More races screened, more candidates researched, and more campaigns operated without abandoning follow-through.</p></article><article className="info-card accent"><h3>Speed</h3><p>Shorter distance between an electoral opening and a public intervention.</p></article><article className="info-card accent"><h3>Force</h3><p>Stronger creative distribution, more visible endorsement, and greater capacity to support selected candidates.</p></article></div></div></section>

    <section className="content-section alt"><div className="content-shell prose-grid"><h2>Current stage and candor.</h2><div className="prose"><p>The PAC is early. Present scale limits how many races it can analyze, campaigns it can operate, and candidates it can support simultaneously.</p><p>That limitation is also the opportunity. Added capacity can alter political reach more visibly than it might inside a mature national institution. Smallness alone is not proof of leverage, so the PAC pairs the proposition with a published method and a growing execution record.</p><h3>What support does not guarantee</h3><ul><li>candidate movement in every campaign;</li><li>endorsement of every UBI supporter;</li><li>victory by every supported candidate;</li><li>donor control over political allocations;</li><li>causal certainty where the evidence cannot provide it.</li></ul></div></div></section>

    <section className="content-section"><div className="content-shell"><h2>Measurement and stewardship</h2><table className="comparison-table"><thead><tr><th>Layer</th><th>Questions</th></tr></thead><tbody><tr><td>Political</td><td>Did candidates respond, clarify, adopt, defend, or act on meaningful UBI?</td></tr><tr><td>Operating</td><td>Did added capacity improve screening, speed, campaign quality, distribution, or follow-through?</td></tr><tr><td>Financial</td><td>Is revenue dependable, diversified, reconciled, and converted into named capabilities?</td></tr><tr><td>Trust</td><td>Are records current, uncertainty visible, corrections prompt, and donor understanding improving?</td></tr></tbody></table><div className="notice-box" style={{marginTop: 24}}><b>Budget discipline:</b> numerical capacity scenarios will be published only after leadership approves the underlying operating budget and assumptions.</div></div></section>

    <section className="content-section"><div className="content-shell action-panel"><h2>Request a substantive briefing.</h2><p>Discuss present work, constraints, leadership, twelve-month capabilities, reporting, and fit. A first conversation does not require an intended contribution amount.</p><div className="hero-actions"><a className="button button-cream" href="mailto:contact@basicallyincome.org?subject=Strategic%20briefing%20request">Request a Strategic Briefing</a><ButtonLink href="/results" variant="outline">Inspect the Work Log</ButtonLink></div></div></section>
  </PageShell>;
}
